// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/micro/enterprise/proto/license.proto

/*
Package enterprise is a generated protocol buffer package.

It is generated from these files:
	github.com/micro/enterprise/proto/license.proto

It has these top-level messages:
	Info
	License
	Service
	Subscription
	Token
	Update
*/
package enterprise

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Info is the response from an update
type Info struct {
	// informational message
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	// unix timestamp of info
	Timestamp uint64 `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	// unix timestamp for next update
	NextUpdate uint64 `protobuf:"varint,3,opt,name=next_update,json=nextUpdate" json:"next_update,omitempty"`
}

func (m *Info) Reset()                    { *m = Info{} }
func (m *Info) String() string            { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()               {}
func (*Info) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Info) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Info) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Info) GetNextUpdate() uint64 {
	if m != nil {
		return m.NextUpdate
	}
	return 0
}

// License is the enterprise license
type License struct {
	// unique id
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// version of license
	Version string `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	// time of creation
	Created uint64 `protobuf:"varint,3,opt,name=created" json:"created,omitempty"`
	// X-Micro-License hash
	Key string `protobuf:"bytes,4,opt,name=key" json:"key,omitempty"`
	// subscription
	Subscription *Subscription `protobuf:"bytes,5,opt,name=subscription" json:"subscription,omitempty"`
}

func (m *License) Reset()                    { *m = License{} }
func (m *License) String() string            { return proto.CompactTextString(m) }
func (*License) ProtoMessage()               {}
func (*License) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *License) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *License) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *License) GetCreated() uint64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *License) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *License) GetSubscription() *Subscription {
	if m != nil {
		return m.Subscription
	}
	return nil
}

// Service is a micro service
type Service struct {
	// name of service
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// version of service
	Version string `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	// unique id of instance
	Id string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
}

func (m *Service) Reset()                    { *m = Service{} }
func (m *Service) String() string            { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()               {}
func (*Service) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Service) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Subscription is a user subscription
type Subscription struct {
	// id of subscription
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// email of associated
	Email string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	// type of subscription
	Type string `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	// status e.g active
	Status string `protobuf:"bytes,4,opt,name=status" json:"status,omitempty"`
	// created at
	Created uint64 `protobuf:"varint,5,opt,name=created" json:"created,omitempty"`
	// quantity e.g services
	Quantity uint64 `protobuf:"varint,6,opt,name=quantity" json:"quantity,omitempty"`
}

func (m *Subscription) Reset()                    { *m = Subscription{} }
func (m *Subscription) String() string            { return proto.CompactTextString(m) }
func (*Subscription) ProtoMessage()               {}
func (*Subscription) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Subscription) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Subscription) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Subscription) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Subscription) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Subscription) GetCreated() uint64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Subscription) GetQuantity() uint64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

// Token is for auth
type Token struct {
	// unique id of token
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// unix timestamp
	Expires uint64 `protobuf:"varint,2,opt,name=expires" json:"expires,omitempty"`
	// various values
	Claims map[string]string `protobuf:"bytes,3,rep,name=claims" json:"claims,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// encrypted key
	Key string `protobuf:"bytes,4,opt,name=key" json:"key,omitempty"`
}

func (m *Token) Reset()                    { *m = Token{} }
func (m *Token) String() string            { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()               {}
func (*Token) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Token) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Token) GetExpires() uint64 {
	if m != nil {
		return m.Expires
	}
	return 0
}

func (m *Token) GetClaims() map[string]string {
	if m != nil {
		return m.Claims
	}
	return nil
}

func (m *Token) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

// Update is a checkpoint
type Update struct {
	// unique id for update
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// unix timestamp
	Timestamp uint64 `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	// service using license
	Service *Service `protobuf:"bytes,3,opt,name=service" json:"service,omitempty"`
}

func (m *Update) Reset()                    { *m = Update{} }
func (m *Update) String() string            { return proto.CompactTextString(m) }
func (*Update) ProtoMessage()               {}
func (*Update) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Update) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Update) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Update) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

func init() {
	proto.RegisterType((*Info)(nil), "enterprise.Info")
	proto.RegisterType((*License)(nil), "enterprise.License")
	proto.RegisterType((*Service)(nil), "enterprise.Service")
	proto.RegisterType((*Subscription)(nil), "enterprise.Subscription")
	proto.RegisterType((*Token)(nil), "enterprise.Token")
	proto.RegisterType((*Update)(nil), "enterprise.Update")
}

func init() { proto.RegisterFile("github.com/micro/enterprise/proto/license.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 424 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0xd1, 0x8a, 0xd3, 0x40,
	0x14, 0x65, 0x9a, 0x26, 0xb5, 0x37, 0x8b, 0xc8, 0xb8, 0xc8, 0xb0, 0x28, 0x96, 0x3c, 0xf5, 0xc5,
	0x04, 0x2a, 0x82, 0x8a, 0x6f, 0x22, 0x22, 0xf8, 0x94, 0xd5, 0xe7, 0x65, 0x9a, 0x5e, 0xd7, 0x61,
	0x3b, 0x93, 0x38, 0x33, 0x29, 0x9b, 0x1f, 0xf1, 0xcd, 0xcf, 0xf0, 0xff, 0x24, 0x93, 0x19, 0x93,
	0xd2, 0xa5, 0x6f, 0x73, 0xee, 0x39, 0x9c, 0x9b, 0x7b, 0xee, 0x0d, 0x14, 0xb7, 0xc2, 0xfe, 0x6c,
	0xb7, 0x79, 0x55, 0xcb, 0x42, 0x8a, 0x4a, 0xd7, 0x05, 0x2a, 0x8b, 0xba, 0xd1, 0xc2, 0x60, 0xd1,
	0xe8, 0xda, 0xd6, 0xc5, 0x5e, 0x54, 0xa8, 0x0c, 0xe6, 0x0e, 0x51, 0x18, 0xf9, 0xec, 0x06, 0xe6,
	0x5f, 0xd4, 0x8f, 0x9a, 0x32, 0x58, 0x48, 0x34, 0x86, 0xdf, 0x22, 0x23, 0x2b, 0xb2, 0x5e, 0x96,
	0x01, 0xd2, 0xe7, 0xb0, 0xb4, 0x42, 0xa2, 0xb1, 0x5c, 0x36, 0x6c, 0xb6, 0x22, 0xeb, 0x79, 0x39,
	0x16, 0xe8, 0x4b, 0x48, 0x15, 0xde, 0xdb, 0x9b, 0xb6, 0xd9, 0x71, 0x8b, 0x2c, 0x72, 0x3c, 0xf4,
	0xa5, 0xef, 0xae, 0x92, 0xfd, 0x21, 0xb0, 0xf8, 0x3a, 0xb4, 0xa7, 0x8f, 0x61, 0x26, 0x76, 0xde,
	0x7f, 0x26, 0x76, 0x7d, 0xd3, 0x03, 0x6a, 0x23, 0x6a, 0xe5, 0x8c, 0x97, 0x65, 0x80, 0x3d, 0x53,
	0x69, 0xe4, 0x16, 0x77, 0xde, 0x32, 0x40, 0xfa, 0x04, 0xa2, 0x3b, 0xec, 0xd8, 0xdc, 0xe9, 0xfb,
	0x27, 0xfd, 0x00, 0x17, 0xa6, 0xdd, 0x9a, 0x4a, 0x8b, 0xc6, 0xf6, 0x56, 0xf1, 0x8a, 0xac, 0xd3,
	0x0d, 0xcb, 0xc7, 0x29, 0xf3, 0xeb, 0x09, 0x5f, 0x1e, 0xa9, 0xb3, 0xcf, 0xb0, 0xb8, 0x46, 0x7d,
	0x10, 0x15, 0x52, 0x0a, 0x73, 0xc5, 0x65, 0x08, 0xc0, 0xbd, 0xcf, 0x7c, 0xe2, 0x30, 0x4c, 0x14,
	0x86, 0xc9, 0x7e, 0x13, 0xb8, 0x98, 0xf6, 0x39, 0x99, 0xf6, 0x12, 0x62, 0x94, 0x5c, 0xec, 0xbd,
	0xd1, 0x00, 0xfa, 0xa6, 0xb6, 0x6b, 0xd0, 0x1b, 0xb9, 0x37, 0x7d, 0x06, 0x89, 0xb1, 0xdc, 0xb6,
	0xc6, 0x8f, 0xe9, 0xd1, 0x34, 0x95, 0xf8, 0x38, 0x95, 0x2b, 0x78, 0xf4, 0xab, 0xe5, 0xca, 0x0a,
	0xdb, 0xb1, 0xc4, 0x51, 0xff, 0x71, 0xf6, 0x97, 0x40, 0xfc, 0xad, 0xbe, 0x43, 0xf5, 0x50, 0xfe,
	0x78, 0xdf, 0x08, 0x8d, 0xc6, 0x2f, 0x36, 0x40, 0xfa, 0x06, 0x92, 0x6a, 0xcf, 0x85, 0x34, 0x2c,
	0x5a, 0x45, 0xeb, 0x74, 0xf3, 0x62, 0x9a, 0xa6, 0x33, 0xcb, 0x3f, 0x3a, 0xfe, 0x93, 0xb2, 0xba,
	0x2b, 0xbd, 0xf8, 0x74, 0x39, 0x57, 0xef, 0x20, 0x9d, 0x08, 0x83, 0x80, 0x8c, 0xdb, 0xbb, 0x84,
	0xf8, 0xc0, 0xf7, 0x2d, 0x86, 0x54, 0x1c, 0x78, 0x3f, 0x7b, 0x4b, 0x32, 0x84, 0x64, 0xb8, 0xa1,
	0x93, 0xef, 0x3e, 0x7f, 0x92, 0xaf, 0x60, 0x61, 0x86, 0x8d, 0xba, 0x50, 0xd3, 0xcd, 0xd3, 0xa3,
	0x53, 0x18, 0xa8, 0x32, 0x68, 0xb6, 0x89, 0xfb, 0x29, 0x5e, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff,
	0x2a, 0xf2, 0x83, 0x0f, 0x47, 0x03, 0x00, 0x00,
}
